services:
  guitarstore.postgres:
    container_name: guitarstore.postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "guitarstoredb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
        
  guitarstore.redis:
    image: redis:latest
    restart: always
    ports: 
      - '6379:6379'

volumes:
  postgres-data:
