services:
  api:
    image: ${DOCKER_REGISTRY-}musicstoreapi
    container_name: MusicStore.Api
    build:
      context: .
      dockerfile: src/Api/MusicStore.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5050:8081"
      
  postgres:
    container_name: MusicStore.Postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "MusicStoreDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
        
  redis:
    container_name: MusicStore.Redis
    image: redis:latest
    restart: always
    ports: 
      - '6379:6379'
        
  rabbitmq:
    container_name: MusicStore.RabbitMq
    image: rabbitmq:management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15627:15672"
    volumes:
      - /var/lib/rabbitmq/data
    networks:
      - rabbitmq
        
  keycloak:
    container_name: MusicStore.Keycloak
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - "18080:8080"

networks:
  rabbitmq:
    driver: bridge
